import { Head, useForm, Link } from '@inertiajs/react';
import { type FormEvent } from 'react';
import AppLayout from '../../Components/AppLayout';
import { Card, PageHeader } from '../../Components/Primitives';
import { getDictionary } from '../../lib/i18n';
import type { SharedPageProps } from '../../Types/page';

type CategoryOption = {
  id: string;
  code: string;
  name: { en: string; ar: string } | string;
  useful_life_months: number;
  salvage_value_minor: number;
};

type CurrencyOption = {
  code: string;
  name: string;
  symbol: string;
};

type CreateProps = SharedPageProps & {
  categories: CategoryOption[];
  currencies: CurrencyOption[];
};

export default function FixedAssetCreate({ locale, categories, currencies }: CreateProps) {
  const dict = getDictionary(locale);
  const appDict = dict.app.accounting;
  const defaultCurrency = currencies[0]?.code || '';

  const { data, setData, post, transform, processing, errors } = useForm({
    asset_number: '',
    name_en: '',
    name_ar: '',
    description: '',
    fixed_asset_category_id: categories[0]?.id || '',
    currency: defaultCurrency,
    acquisition_date: new Date().toISOString().split('T')[0],
    in_service_date: new Date().toISOString().split('T')[0],
    cost_minor: 100000,
    salvage_value_minor: categories[0]?.salvage_value_minor || 0,
    useful_life_months: categories[0]?.useful_life_months || 60,
    opening_accumulated_depreciation_minor: 0,
    serial_number: '',
  });

  function handleCategoryChange(catId: string) {
    const selected = categories.find((c) => c.id === catId);
    setData((prev) => ({
      ...prev,
      fixed_asset_category_id: catId,
      useful_life_months: selected ? selected.useful_life_months : prev.useful_life_months,
      salvage_value_minor: selected ? selected.salvage_value_minor : prev.salvage_value_minor,
    }));
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    transform((formData) => ({
      asset_number: formData.asset_number,
      name: { en: formData.name_en, ar: formData.name_ar },
      description: formData.description,
      fixed_asset_category_id: formData.fixed_asset_category_id,
      currency: formData.currency,
      acquisition_date: formData.acquisition_date,
      in_service_date: formData.in_service_date,
      cost_minor: formData.cost_minor,
      salvage_value_minor: formData.salvage_value_minor,
      useful_life_months: formData.useful_life_months,
      opening_accumulated_depreciation_minor: formData.opening_accumulated_depreciation_minor,
      serial_number: formData.serial_number,
    }));
    post('/fixed-assets');
  }

  function formatCatName(name: { en: string; ar: string } | string): string {
    if (typeof name === 'object' && name !== null) {
      return locale === 'ar' ? name.ar || name.en : name.en || name.ar;
    }
    return String(name);
  }

  return (
    <AppLayout active="fixed-assets.index">
      <Head title={`${appDict.createFixedAsset} - ${appDict.appName}`} />

      <div className="max-w-4xl mx-auto space-y-6">
        <PageHeader
          title={appDict.createFixedAsset}
          description={appDict.fixedAssets}
          actions={
            <Link
              href="/fixed-assets"
              className="px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-md hover:bg-slate-50 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700"
            >
              {appDict.back}
            </Link>
          }
        />

        <Card>
          <form onSubmit={handleSubmit} className="p-6 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.assetNumber} ({appDict.autoGeneratedIfBlank})
                </label>
                <input
                  type="text"
                  placeholder="FA-2026-00001"
                  value={data.asset_number}
                  onChange={(e) => setData('asset_number', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 font-mono text-sm"
                />
                {errors.asset_number && <p className="mt-1 text-xs text-rose-600">{errors.asset_number}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.assetCategory}
                </label>
                <select
                  value={data.fixed_asset_category_id}
                  onChange={(e) => handleCategoryChange(e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                >
                  {categories.map((cat) => (
                    <option key={cat.id} value={cat.id}>
                      {formatCatName(cat.name)} ({cat.code})
                    </option>
                  ))}
                </select>
                {errors.fixed_asset_category_id && <p className="mt-1 text-xs text-rose-600">{errors.fixed_asset_category_id}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.englishName}
                </label>
                <input
                  type="text"
                  value={data.name_en}
                  onChange={(e) => setData('name_en', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.arabicName}
                </label>
                <input
                  type="text"
                  value={data.name_ar}
                  onChange={(e) => setData('name_ar', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.acquisitionDate}
                </label>
                <input
                  type="date"
                  value={data.acquisition_date}
                  onChange={(e) => setData('acquisition_date', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.inServiceDate}
                </label>
                <input
                  type="date"
                  value={data.in_service_date}
                  onChange={(e) => setData('in_service_date', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.historicalCost}
                </label>
                <input
                  type="number"
                  min="1"
                  value={data.cost_minor}
                  onChange={(e) => setData('cost_minor', parseInt(e.target.value, 10) || 0)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
                {errors.cost_minor && <p className="mt-1 text-xs text-rose-600">{errors.cost_minor}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.salvageValue}
                </label>
                <input
                  type="number"
                  min="0"
                  value={data.salvage_value_minor}
                  onChange={(e) => setData('salvage_value_minor', parseInt(e.target.value, 10) || 0)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
                {errors.salvage_value_minor && <p className="mt-1 text-xs text-rose-600">{errors.salvage_value_minor}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.usefulLifeMonths}
                </label>
                <input
                  type="number"
                  min="1"
                  value={data.useful_life_months}
                  onChange={(e) => setData('useful_life_months', parseInt(e.target.value, 10) || 1)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                  required
                />
                {errors.useful_life_months && <p className="mt-1 text-xs text-rose-600">{errors.useful_life_months}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.openingAccumulatedDepreciation}
                </label>
                <input
                  type="number"
                  min="0"
                  value={data.opening_accumulated_depreciation_minor}
                  onChange={(e) => setData('opening_accumulated_depreciation_minor', parseInt(e.target.value, 10) || 0)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                />
                {errors.opening_accumulated_depreciation_minor && <p className="mt-1 text-xs text-rose-600">{errors.opening_accumulated_depreciation_minor}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.currency}
                </label>
                <select
                  value={data.currency}
                  onChange={(e) => setData('currency', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                >
                  {currencies.map((curr) => (
                    <option key={curr.code} value={curr.code}>
                      {curr.code} - {curr.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                  {appDict.serialNumber}
                </label>
                <input
                  type="text"
                  value={data.serial_number}
                  onChange={(e) => setData('serial_number', e.target.value)}
                  className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                {appDict.description}
              </label>
              <textarea
                rows={3}
                value={data.description}
                onChange={(e) => setData('description', e.target.value)}
                className="w-full mt-1 rounded-md border-slate-300 dark:bg-slate-900 dark:border-slate-700 text-sm"
              />
            </div>

            <div className="flex justify-end space-x-3 rtl:space-x-reverse pt-4 border-t border-slate-200 dark:border-slate-700">
              <Link
                href="/fixed-assets"
                className="px-4 py-2 text-sm font-medium text-slate-700 bg-slate-100 rounded-md hover:bg-slate-200"
              >
                {appDict.back}
              </Link>
              <button
                type="submit"
                disabled={processing}
                className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700 disabled:opacity-50"
              >
                {appDict.saveAsset}
              </button>
            </div>
          </form>
        </Card>
      </div>
    </AppLayout>
  );
}
